# Generated by Django 6.0.4 on 2026-05-18 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=100)),
                ("ano_inicio", models.IntegerField()),
                ("ano_fim", models.IntegerField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Interesse"),
                ),
                (
                    "icone",
                    models.ImageField(blank=True, null=True, upload_to="interesses/"),
                ),
            ],
            options={
                "verbose_name": "Interesse",
                "verbose_name_plural": "Interesses",
            },
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("apresentacao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("etapa", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("decisao", models.TextField(blank=True)),
                ("uso_ia", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("acronymo", models.CharField(blank=True, max_length=10)),
                (
                    "logotipo",
                    models.ImageField(blank=True, null=True, upload_to="Tecnologias/"),
                ),
                ("link_website", models.URLField(blank=True)),
                (
                    "nivel_interesse",
                    models.IntegerField(default=1, help_text="Escala de 1 a 5"),
                ),
                ("relevancia", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autores", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="tfc/")),
                ("link_relatorio", models.URLField(blank=True)),
                ("link_github", models.URLField(blank=True)),
                ("video_demo", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Projecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("conceitos_aplicados", models.TextField(blank=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("link_github", models.URLField(blank=True)),
                ("video_demo", models.URLField(blank=True)),
                ("tecnologias", models.ManyToManyField(to="portfolio.tecnologia")),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "logotipo",
                    models.ImageField(blank=True, null=True, upload_to="competencias/"),
                ),
                (
                    "projetos",
                    models.ManyToManyField(blank=True, to="portfolio.projecto"),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("semestre", models.CharField(max_length=20)),
                ("ects", models.IntegerField(default=6)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                ("link_docente_lusofona", models.URLField(blank=True)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projecto",
            name="unidade_curricular",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.unidadecurricular",
            ),
        ),
    ]
