# Generated by Django 6.0.4 on 2026-05-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interesse",
            name="descricao",
            field=models.TextField(default="", verbose_name="Descrição"),
        ),
        migrations.AddField(
            model_name="interesse",
            name="disciplinas",
            field=models.ManyToManyField(blank=True, to="portfolio.unidadecurricular"),
        ),
        migrations.AddField(
            model_name="interesse",
            name="e_preferido",
            field=models.BooleanField(
                default=False, verbose_name="É a área preferida?"
            ),
        ),
        migrations.AddField(
            model_name="interesse",
            name="projetos",
            field=models.ManyToManyField(blank=True, to="portfolio.projecto"),
        ),
        migrations.AddField(
            model_name="interesse",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
    ]
