# Generated by Django 6.0.3 on 2026-04-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenciatura",
            name="apresentação",
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="apresentacao",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projecto",
            name="conceitos_aplicados",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projecto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="projetos/"),
        ),
        migrations.AddField(
            model_name="projecto",
            name="link_github",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="projecto",
            name="video_demo",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="acronymo",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="link_website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="logotipo",
            field=models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="ects",
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="link_docente_lusofona",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.CharField(default="1º Semestre", max_length=20),
            preserve_default=False,
        ),
    ]
