# Generated by Django 6.0.3 on 2026-04-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_licenciatura_apresentação_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "logotipo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("etapa", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autores", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="tfc/")),
                ("link_relatorio", models.URLField(blank=True)),
                ("link_github", models.URLField(blank=True)),
                ("video_demo", models.URLField(blank=True)),
            ],
        ),
    ]
