# Generated by Django 6.0.4 on 2026-05-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_competencia_makingof_tfc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=100)),
                ("ano_inicio", models.IntegerField()),
                ("ano_fim", models.IntegerField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                (
                    "icone",
                    models.ImageField(blank=True, null=True, upload_to="interesses/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="competencia",
            name="projetos",
            field=models.ManyToManyField(blank=True, to="portfolio.projecto"),
        ),
        migrations.AddField(
            model_name="competencia",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
        migrations.AddField(
            model_name="makingof",
            name="decisao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="makingof",
            name="uso_ia",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="nivel_interesse",
            field=models.IntegerField(default=1, help_text="Escala de 1 a 5"),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="relevancia",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="logotipo",
            field=models.ImageField(blank=True, null=True, upload_to="competencias/"),
        ),
    ]
